tap "homebrew/cask-fonts"
tap "homebrew/bundle"
tap "hashicorp/tap"

cask "zoom"
cask "wezterm"
cask "visual-studio-code"
cask "ssh-tunnel-manager"
cask "spotify"
cask "rectangle"
cask "raycast"
cask "obsidian"
cask "iterm2"
cask "insomnia"
cask "google-chrome"
cask "font-monaspace-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "firefox"
cask "1password-cli"
brew "zsh"
brew "zsh-completions"
brew "yq"
brew "wget"
brew "watch"
brew "tree"
brew "tmuxinator"
brew "tmux"
brew "the_silver_searcher"
brew "tflint"
brew "telnet"
brew "stow"
brew "ripgrep"
brew "reattach-to-user-namespace"
brew "neovim"
brew "mas"
brew "markdownlint-cli"
brew "jsonlint"
brew "jq"
brew "httpie"
brew "hashicorp/tap/terraform"
brew "go"
brew "gnupg"
brew "git"
brew "fzf"
brew "fd"
brew "dos2unix"
brew "direnv"
brew "curl"
brew "bat"

mas "tailscale", id: 1475387142
mas "microsoft-to-do", id: 1274495053
mas "1password-for-safari", id: 1569813296

#Visual
vscode "vscodevim.vim"
vscode "mads-hartmann.bash-ide-vscode"
vscode "hashicorp.terraform"
vscode "enkia.tokyo-night"