export XDG_CONFIG_HOME=${HOME}/.config/
export ZSH_CONFIG_PATH=${XDG_CONFIG_HOME}/zsh

# Create ZSH_CONFIG_PATH if it doesn't exist
if [ ! -d "${ZSH_CONFIG_PATH}" ]; then
    mkdir -p "${ZSH_CONFIG_PATH}"
fi

# All personal configuration files are stored in $ZSH_CONFIG_PATH/zsh/*.zsh
for file in ${ZSH_CONFIG_PATH}/*.zsh; do
    source "$file"
done

export PATH=${HOME}/bin:${HOME}/.local/bin/nvim/bin:/usr/local/bin:${PATH}
export PATH=${HOME}/.local/bin:/usr/local/opt/curl/bin:${PATH}

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"


ZSH_THEME="clean"
DISABLE_AUTO_UPDATE="true"

export HISTFILE=${HOME}/.zsh_history
export HISTSIZE=300000
export SAVEHIST=${HISTSIZE}
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify
setopt hist_ignore_space
setopt append_history
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt no_beep
setopt inc_append_history

plugins=(git terraform fzf aws 1password)

source $ZSH/oh-my-zsh.sh

# history configuration

export EDITOR="nvim"
export VISUAL="nvim"
export GIT_EDITOR="nvim"
export HIST_STAMPS="yyyy-mm-dd"

# FZF specific - https://github.com/junegunn/fzf#key-bindings-for-command-line
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --no-ignore-vcs"
export FZF_DEFAULT_OPTS="--height 75% --layout=reverse --border"
export FZF_CTRL_T_COMMAND=${FZF_DEFAULT_COMMAND}
export FZF_ALT_C_COMMAND="fd --type d . --color=never"

export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} \
--color=fg:#c0caf5,bg:#1a1b26,hl:#ff9e64 \
--color=fg+:#c0caf5,bg+:#292e42,hl+:#ff9e64 \
--color=info:#7aa2f7,prompt:#7dcfff,pointer:#7dcfff \
--color=marker:#9ece6a,spinner:#9ece6a,header:#9ece6a"

export TFLINT_CONFIG_FILE="${HOME}/.dotfiles/master/tflint/tflint.hcl"

bindkey -s ^f "~/.local/bin/tmux-sessionizer\n"
